# Generated by Django 4.1.3 on 2022-11-09 09:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drf', '0003_alter_profile_account_alter_profile_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='inn',
            field=models.CharField(max_length=15, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('user', 'inn')},
        ),
    ]
