# Generated by Django 4.1.3 on 2022-11-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0004_alter_profile_inn_alter_profile_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='inn',
            field=models.IntegerField(max_length=15, null=True, verbose_name='ИНН'),
        ),
    ]
