# Generated by Django 4.1.3 on 2022-11-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0005_alter_profile_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='inn',
            field=models.CharField(max_length=15, null=True, verbose_name='ИНН'),
        ),
    ]
